# permissions for end users to edit trusteddomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trusteddomain-editor-role
rules:
- apiGroups:
  - okta.com
  resources:
  - trusteddomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okta.com
  resources:
  - trusteddomains/status
  verbs:
  - get
