apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: okta-controller.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TrustedDomain is the Schema for the trusteddomains API
      displayName: Trusted Domain
      kind: TrustedDomain
      name: trusteddomains.okta.com
      version: v1alpha1
  description: Operator for okta
  displayName: okta
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - okta
  links:
  - name: Okta Controller
    url: https://okta-controller.domain
  maturity: alpha
  provider:
    name: kanzifucius
  version: 0.0.0
