name: '🚀 main-ci'
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - 'master'

concurrency:
  group: main-ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        run: make docker-build
      - name: Build Image
        run: make docker-push
